const records={
  'office-management':{title:'Office Management System',domain:'Operations / Internal tools',role:'Product design',summary:'A digital workspace designed to make everyday office operations easier to request, coordinate, and track.',accent:'#789988',images:[['https://cdn.dribbble.com/userupload/48387870/file/e678268c3dbf4a37043cbca2f7ddbced.png','Office Management System interface overview'],['https://cdn.dribbble.com/userupload/48439455/file/3d73c66c8d5240751425741fa80a2475.png','Office Management System workflow screen'],['https://cdn.dribbble.com/userupload/48439479/file/e15d5673b3b37a7ae9d6b1dff2ecbf57.png','Office Management System detail screen']],sections:[
    ['Project overview','An internal operations product that brings facilities requests, visitor coordination, room bookings, and workplace uLYDIAates into one clear workspace. My role covered the end-to-end experience, from workflow mapping to interface design.'],
    ['The Challenge','Office teams often manage requests through disconnected messages, spreadsheets, and email. This creates duplicate work, limited visibility, and uncertainty for both employees and operations teams.'],
    ['Goals and Objectives','Create a simple entry point for common requests, make ownership and status visible, and give operations teams a reliable view of work in progress without adding unnecessary process.'],
    ['Research and Discovery','I mapped the request journey with people who submit, manage, and complete office tasks. The research highlighted recurring handoffs, unclear request categories, and a need for transparent status uLYDIAates.'],
    ['Design Process','I translated the journey into a small set of task flows, tested clearer request language and prioritisation patterns, then developed responsive screens and reusable components with implementation in mind.'],
    ['Impact and Solutions','The resulting concept centralises operational work around a shared request record, clear ownership, and timely uLYDIAates. It creates a foundation for more consistent workplace support and easier team coordination.'],
    ['Design Snapshots','Show the request dashboard, a guided submission flow, task-detail states, and the operational view used to prioritise and resolve work.']
  ]},
  'community-board':{title:'Community Board',domain:'Community / Responsive web',role:'UX & interaction design',summary:'A community space that helps people discover relevant uLYDIAates, share opportunities, and participate with confidence.',accent:'#b47650',sections:[
    ['Project overview','A responsive community platform for announcements, discussions, local opportunities, and events. The project focused on making useful information easy to find while keeping participation welcoming.'],
    ['The Challenge','Community information can quickly become fragmented or overwhelming. People need to know what is relevant to them, while contributors need a straightforward way to share without creating noise.'],
    ['Goals and Objectives','Improve content discovery, create a clear path to contribute, and establish lightweight structure that helps members understand where conversations belong.'],
    ['Research and Discovery','I reviewed common browsing and posting behaviours, considered how people assess relevance, and identified the importance of filters, concise summaries, and clear signals of activity.'],
    ['Design Process','I explored information architecture, category language, content-card hierarchy, and posting flows. Prototypes were used to refine scanning, filtering, and the balance between discovery and contribution.'],
    ['Impact and Solutions','The design provides focused pathways for browsing, sharing, and returning to active conversations. A consistent content system helps community information feel organised without becoming restrictive.'],
    ['Design Snapshots','Include the community feed, category exploration, a post-detail view, contribution flow, and mobile responsive states.']
  ]},
  'game-design':{title:'Game Design',domain:'Gaming / Interaction design',role:'Game UX & visual design',summary:'A game experience shaped around readable rules, motivating progression, and interactions that stay out of the player’s way.',accent:'#787ba9',sections:[
    ['Project overview','A game-design case study focused on the player journey: understanding the core loop, making choices feel meaningful, and supporting play through a coherent visual and interaction system.'],
    ['The Challenge','Players need to understand what to do next without losing the sense of discovery. Too much instruction interrupts flow, while too little can make early play confusing or discouraging.'],
    ['Goals and Objectives','Clarify the onboarding experience, make game states and feedback easier to read, and support a progression system that keeps the player oriented and motivated.'],
    ['Research and Discovery','I examined the game loop, moments of player uncertainty, feedback patterns, and comparable interaction conventions. This informed hypotheses around pacing, prompts, and visual hierarchy.'],
    ['Design Process','The work moved from flow diagrams and low-fidelity screens into interaction prototypes and visual explorations. I iterated on navigation, moment-to-moment feedback, and the relationship between play and progression.'],
    ['Impact and Solutions','The final direction gives players clearer cues at key decisions while preserving a playful sense of discovery. The component approach also makes states and feedback more consistent across the experience.'],
    ['Design Snapshots','Show the onboarding sequence, core game loop, feedback and reward states, pause or settings screens, and the progression interface.']
  ]},
  'endorphin-health':{title:'Endorphin Health App',domain:'Health & wellness / Mobile',role:'Mobile product design',summary:'A health and wellbeing companion designed to make small, positive routines feel practical, personal, and sustainable.',accent:'#a89a7a',images:[['https://cdn.dribbble.com/userupload/48439559/file/bc366c685541f99140ae6960762f7c2e.png?format=webp&resize=400x300&vertical=center','Endorphin Health App overview screen'],['https://cdn.dribbble.com/userupload/48378462/file/279f1a37c841a9dfa81ce0d6ea571ab8.png?format=webp&resize=400x300&vertical=center','Endorphin Health App routine screen'],['https://cdn.dribbble.com/userupload/48439475/file/4dfdc36feb46749b08cfe7121a847b22.png?format=webp&resize=400x300&vertical=center','Endorphin Health App progress screen']],sections:[
    ['Project overview','A mobile health app concept that supports people in building wellbeing routines, checking in with how they feel, and finding manageable next steps.'],
    ['The Challenge','Health tools can feel demanding, overly clinical, or disconnected from daily life. People need support that is clear and encouraging without implying that wellbeing is a simple checklist.'],
    ['Goals and Objectives','Create a low-pressure daily experience, help users recognise patterns over time, and provide guidance that feels understandable, respectful, and actionable.'],
    ['Research and Discovery','I considered common barriers to habit-building, the emotional tone of health interfaces, and the importance of clarity around progress, privacy, and user control.'],
    ['Design Process','I designed a lightweight check-in, routine suggestions, progress views, and reminder preferences. The flows were refined to reduce cognitive load and to make each action feel optional and achievable.'],
    ['Impact and Solutions','The proposed experience turns wellbeing support into a series of small, understandable interactions. It gives users a clearer view of their routines while maintaining a calm and non-judgemental tone.'],
    ['Design Snapshots','Include onboarding and consent, the daily check-in, routine recommendations, progress reflections, and reminder controls.']
  ]},
  'insurance-app':{title:'Insurance App',domain:'Insurance / Mobile & web',role:'End-to-end product design',summary:'An insurance experience designed to help people understand coverage, manage policies, and take action when it matters.',accent:'#5e918e',sections:[
    ['Project overview','A digital insurance product that brings policy information, claims support, and account management into a more understandable customer experience.'],
    ['The Challenge','Insurance language, policy details, and claims processes can be difficult to navigate, particularly when people need help quickly. The experience needs to feel trustworthy without oversimplifying important information.'],
    ['Goals and Objectives','Help customers understand their coverage, make essential actions easy to find, and create supportive guided paths for policy changes and claims-related tasks.'],
    ['Research and Discovery','I mapped key customer moments, including checking cover, uLYDIAating personal details, and starting a claim. The discovery work focused on uncertainty, terminology, and the information people need at each step.'],
    ['Design Process','I developed a clearer account structure, plain-language policy summaries, and step-by-step service flows. Prototypes tested hierarchy, confirmation states, and ways to surface help without interrupting the task.'],
    ['Impact and Solutions','The solution gives customers a more direct route to policy information and priority tasks. It pairs clear explanations with guided actions, creating a calmer and more transparent insurance experience.'],
    ['Design Snapshots','Show the policy overview, coverage details, claims entry point, guided claim steps, support pathways, and responsive account screens.']
  ]}
};
const item=records[new URLSearchParams(location.search).get('id')]||records['office-management'];
document.title=`${item.title} - Case study`;document.querySelector('#case-title').textContent=item.title;document.querySelector('#case-domain').textContent=item.domain;document.querySelector('#case-summary').textContent=item.summary;document.querySelector('#case-tags').innerHTML=`<span>${item.role}</span><span>3-year portfolio</span><span>Case study</span>`;
const ids=['overview','challenge','goals','research','process','impact','snapshots'];
const snapshots=item.images?`<div class="snapshot-grid image-snapshots">${item.images.map(([src,alt])=>`<button class="snapshot-image" type="button" data-image="${src}" data-alt="${alt}" aria-label="Expand ${alt}"><img src="${src}" alt="${alt}" loading="lazy"></button>`).join('')}</div><a class="supporting-link" href="https://drive.google.com/file/d/1zPmy1d26vRxPrmOS3AzMEjlGAGNSc1TD/preview" target="_blank" rel="noopener noreferrer">View supporting document ↗</a>`:`<div class="snapshot-grid" style="--snapshot-accent:${item.accent}"><div>Key flow</div><div>Interaction</div><div>Final state</div></div>`;
document.querySelector('#case-sections').innerHTML=item.sections.map(([title,text],index)=>`<section class="case-section" id="${ids[index]}"><p class="section-number">0${index+1}</p><div><h2>${title}</h2><p>${text}</p>${index===6?snapshots:''}</div></section>`).join('');
const imageButtons=[...document.querySelectorAll('.snapshot-image')];
function openGallery(startIndex){let current=startIndex;const modal=document.createElement('dialog');modal.className='image-modal';modal.innerHTML='<button class="gallery-close" type="button" aria-label="Close image viewer">×</button><button class="gallery-nav previous" type="button" aria-label="Previous image">←</button><figure><img alt=""><figcaption></figcaption></figure><button class="gallery-nav next" type="button" aria-label="Next image">→</button>';document.body.append(modal);const image=modal.querySelector('img'),caption=modal.querySelector('figcaption');function render(){const source=imageButtons[current];image.src=source.dataset.image;image.alt=source.dataset.alt;caption.textContent=`${current+1} / ${imageButtons.length} — ${source.dataset.alt}`}function move(direction){current=(current+direction+imageButtons.length)%imageButtons.length;render()}render();modal.showModal();modal.querySelector('.gallery-close').focus();modal.querySelector('.previous').addEventListener('click',()=>move(-1));modal.querySelector('.next').addEventListener('click',()=>move(1));modal.addEventListener('click',event=>{if(event.target===modal||event.target.classList.contains('gallery-close'))modal.close()});modal.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();move(-1)}if(event.key==='ArrowRight'){event.preventDefault();move(1)}});modal.addEventListener('close',()=>modal.remove())}
imageButtons.forEach((button,index)=>button.addEventListener('click',()=>openGallery(index)));
document.querySelector('#year').textContent=new Date().getFullYear();const toggle=document.querySelector('.theme-toggle');toggle.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')});if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark');
